name: Toto
on: [push]
jobs:
  MonPremierJob:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du Repo
        uses: actions/checkout@v3 #utilise le repo (possibilité de spe une version)
      - name: Afficher le contenu de mon job
        run: exit 1 #création erreure
      - name: Envoi mail
        if: ${{ failure() }}
        run: echo "Envoi d'un mail si le test échoue"
  # Build:
  #   needs: [MonPremierJob] #attente du premier job pour lancer le Build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: build de l'app
  #       run: echo "Je build"
